<a href="https://colab.research.google.com/github/LeonimerMelo/python/blob/Pytorch/Pytorch_Tensors_tutorial_v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch -q

In [1]:
import torch
import numpy as np

In [14]:
data = [[1, 2],[3, 4]]
print('data:', data, '\ndata type:', type(data))
x_data = torch.tensor(data)
print('\ntensor:\n', x_data, '\nx_data type:', type(x_data))
np_array = np.array(data)
print('\nnp array:\n', np_array, '\nnp_array type:', type(np_array))
x_np = torch.from_numpy(np_array)
print('\ntensor form np array:\n', x_np, '\nx_np type:', type(x_np))
np_x = x_np.numpy()
print('\nnp array from tensor:\n', np_x, '\nnp_x type:', type(np_x))

data: [[1, 2], [3, 4]] 
data type: <class 'list'>

tensor:
 tensor([[1, 2],
        [3, 4]]) 
x_data type: <class 'torch.Tensor'>

np array:
 [[1 2]
 [3 4]] 
np_array type: <class 'numpy.ndarray'>

tensor form np array:
 tensor([[1, 2],
        [3, 4]]) 
x_np type: <class 'torch.Tensor'>

np array from tensor:
 [[1 2]
 [3 4]] 
np_x type: <class 'numpy.ndarray'>


In [11]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"\nOnes Tensor: \n {x_ones}")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])


In [12]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor:\n{x_rand}")

Random Tensor:
tensor([[0.7244, 0.7558],
        [0.9382, 0.6647]])


In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3593, 0.0562, 0.8433],
        [0.1889, 0.7287, 0.2790]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
tensor = torch.rand(3,4)
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.5414, 0.7258, 0.8946, 0.5034],
        [0.5641, 0.8288, 0.5182, 0.3743],
        [0.8911, 0.3693, 0.5956, 0.7441]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [ ]:
tensor = torch.ones(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


In [ ]:
tensor[:,1] = 0
print(tensor)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
a = torch.tensor([[1,1],[2,2]], dtype=float)
print(a)
b = a.T
print(b)

tensor([[1., 1.],
        [2., 2.]], dtype=torch.float64)
tensor([[1., 2.],
        [1., 2.]], dtype=torch.float64)


In [ ]:
# This computes the matrix multiplication between two tensors.
y1 = a @ b
print(y1)

tensor([[2., 4.],
        [4., 8.]], dtype=torch.float64)


In [ ]:
# This computes the element-wise product.
z1 = a * b
print(z1)
z2 = a.mul(b)
print(z2)

tensor([[1., 2.],
        [2., 4.]], dtype=torch.float64)
tensor([[1., 2.],
        [2., 4.]], dtype=torch.float64)


In [ ]:
y2 = torch.rand_like(a)
print(y2)
torch.mul(a, b, out=y2)
print(y2)

tensor([[0.3761, 0.7811],
        [0.0748, 0.3160]], dtype=torch.float64)
tensor([[1., 2.],
        [2., 4.]], dtype=torch.float64)


In [ ]:
y3 = a.matmul(b)
print(y3)

tensor([[2., 4.],
        [4., 8.]], dtype=torch.float64)


In [ ]:
y4 = torch.rand_like(a)
print(y4)
y5 = torch.matmul(a, b, out=y4)
print(y5)

tensor([[0.9467, 0.7889],
        [0.7071, 0.6122]], dtype=torch.float64)
tensor([[2., 4.],
        [4., 8.]], dtype=torch.float64)


In [ ]:
agg = a.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

6.0 <class 'float'>


In [ ]:
print(f"{a} \n")
# copy a tensor and detach from the computation graph
c = a.clone().detach()
print(c)
c.add_(5)
print(c)

tensor([[1., 1.],
        [2., 2.]], dtype=torch.float64) 

tensor([[1., 1.],
        [2., 2.]], dtype=torch.float64)
tensor([[6., 6.],
        [7., 7.]], dtype=torch.float64)


In [ ]:
x = torch.zeros(2, 1, 2, 1, 2).int()
print(x.size())
# Returns a tensor with all specified dimensions of input of size 1 removed
y = torch.squeeze(x)
print(y.size())
# Returns a new tensor with a dimension of size one inserted at the specified position.
y1 = torch.unsqueeze(y, 0)
print(y1.size())
print(y1.type())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([1, 2, 2, 2])
torch.IntTensor


In [ ]:
y2 = y.unsqueeze(1)
print(y2.shape)

torch.Size([2, 1, 2, 2])


In [ ]:
y3 = torch.unsqueeze(y, 2).float()
print(y3.size())
print(y3.type())

torch.Size([2, 2, 1, 2])
torch.FloatTensor


In [ ]:
# squeeze(input, 0) leaves the tensor unchanged
y = torch.squeeze(x, 0)
print(y.size())
# squeeze(input, n) will squeeze size 1 of tensor on first 'n' dimension shape
y = torch.squeeze(x, 1)
print(y.size())
z = torch.squeeze(y, 2)
print(z.size())
y = torch.squeeze(x, (1, 2, 3))
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])


In [ ]:
# np array
print(x.shape)
s = np.expand_dims(x, axis=0)
print(s.shape)
s = np.expand_dims(x, axis=-1)
print(s.shape)

torch.Size([2, 1, 2, 1, 2])
(1, 2, 1, 2, 1, 2)
(2, 1, 2, 1, 2, 1)


In [ ]:
# Returns a view of the original tensor input with its dimensions permuted.
x1 = torch.zeros(1, 2, 3, 4)
print(x1.size())
s = torch.permute(x1, (3, 2, 0, 1))
print(s.shape)

torch.Size([1, 2, 3, 4])
torch.Size([4, 3, 1, 2])
